openapi: 3.0.0
info:
  title: Get Wallet Token Balance
  version: 1.0.0
paths:
  /alchemy/token/getWalletTokenBalance:
    get:
      summary: Get token balances for a wallet
      parameters:
        - name: alchemyNetwork
          in: query
          required: true
          description: Alchemy network (mainnet, rinkeby, etc.)
          schema:
            type: string
        - name: address
          in: query
          required: true
          description: Wallet address
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                # Define the schema for the response JSON here

        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
