# owned.tsx
openapi: 3.0.0
info:
  title: Get Owned NFTs
  version: 1.0.0
paths:
  /api/nft/owned:
    get:
      summary: Get a list of owned NFTs
      parameters:
        - name: address
          in: query
          required: true
          schema:
            type: string
        - name: chainId
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: Successfully retrieved owned NFTs
          content:
            application/json:
              schema:
                type: object
                properties:
                  nfts:
                    type: array
                    items:
                      type: object
