# activeListings.tsx
openapi: 3.0.0
info:
  title: Get Active Listings for User
  version: 1.0.0
paths:
  /api/marketplace/activeListings:
    get:
      summary: Get active listings for a user
      parameters:
        - name: address
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: Successfully retrieved active listings
          content:
            application/json:
              schema:
                type: object
                properties:
                  nfts:
                    type: array
                    items:
                      type: object
