openapi: 3.0.0
info:
  title: Get Highest Bid for Listing
  version: 1.0.0
paths:
  /api/marketplace/highestBid:
    get:
      summary: Get highest bid for a listing
      parameters:
        - name: listingId
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: Successfully retrieved highest bid
          content:
            application/json:
              schema:
                type: object