openapi: 3.0.0
info:
  title: Get Sales Volume
  version: 1.0.0
paths:
  /api/marketplace/salesVol:
    get:
      summary: Get sales volume
      responses:
        200:
          description: Successfully retrieved sales volume
          content:
            application/json:
              schema:
                type: object
