# createAuction.tsx
openapi: 3.0.0
info:
  title: Create Auction Listing
  version: 1.0.0
paths:
  /api/marketplace/createAuction:
    post:
      summary: Create an auction listing
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                assetContractAddress:
                  type: string
                tokenId:
                  type: string
                startTimestamp:
                  type: string
                listingDurationInSeconds:
                  type: string
                quantity:
                  type: string
                currencyContractAddress:
                  type: string
                buyoutPricePerToken:
                  type: string
                reservePricePerToken:
                  type: string
      responses:
        200:
          description: Successfully created auction listing
          content:
            application/json:
              schema:
                type: object
                properties:
                  createAuction:
                    type: object
