# floorPrice.tsx
openapi: 3.0.0
info:
  title: Get Floor Price for Collection
  version: 1.0.0
paths:
  /api/marketplace/floorPrice:
    get:
      summary: Get floor price for a collection
      parameters:
        - name: address
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: Successfully retrieved floor price
          content:
            application/json:
              schema:
                type: object
                properties:
                  floorPrice:
                    type: number
                  currencySymbol:
                    type: string
