openapi: 3.0.0
info:
  title: Get Listing by Listing ID
  version: 1.0.0
paths:
  /api/marketplace/listingById:
    get:
      summary: Get listing by listing ID
      parameters:
        - name: listingId
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: Successfully retrieved listing
          content:
            application/json:
              schema:
                type: object