openapi: 3.0.0
info:
  title: Analytics API - listings
  version: 1.0.0
paths:
  /api/analytics/listings:
    get:
      summary: Get analytics for listings
      parameters:
        - name: address
          in: query
          description: Seller's wallet address
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                presentWeek:
                  listings: [5, 3, 7, 2, 0, 1, 9]
                  count: 27
                lastWeek:
                  listings: [3, 1, 4, 0, 2, 1, 6]
                  count: 17
                growthPercent: 58.82
                total:
                  all: 55
                  active: 25
